services:
  mongodb:
    image: mongo:8
    container_name: trackintern-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: trackintern
    volumes:
      - trackintern-mongodb-data:/data/db

volumes:
  trackintern-mongodb-data: